#!/usr/bin/env bash
set -euo pipefail

REPOSITORY="polaris-data/cli"
REQUESTED_VERSION=""
INSTALL_DIR_OVERRIDE=""
TEMPORARY=""

usage() {
  cat <<'EOF'
Usage: install.sh [--version <tag>] [--install-dir <path>]

Install the Polaris standalone executable from GitHub Releases.
By default, installs the latest stable release for this platform.

Options:
  --version <tag>      Install a specific release tag, for example: v0.8.3
  --install-dir <dir>  Install the polaris executable into this directory
  -h, --help           Show this help text

Environment:
  POLARIS_INSTALL_DIR  Install directory used by the generated Polaris installer
  INSTALL_DIR          Generic install-directory fallback
EOF
}

fail() {
  printf 'polaris-install: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

cleanup() {
  if [[ -n "$TEMPORARY" && -d "$TEMPORARY" ]]; then
    rm -rf -- "$TEMPORARY"
  fi
}

normalize_version() {
  case "$1" in
    v*) printf '%s\n' "$1" ;;
    *) printf 'v%s\n' "$1" ;;
  esac
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --version)
        [[ $# -ge 2 ]] || fail "--version requires a value"
        REQUESTED_VERSION="$(normalize_version "$2")"
        shift 2
        ;;
      --install-dir)
        [[ $# -ge 2 ]] || fail "--install-dir requires a value"
        INSTALL_DIR_OVERRIDE="$2"
        shift 2
        ;;
      --runtime-dir)
        fail "--runtime-dir is no longer supported; Polaris now installs one standalone executable"
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        fail "unknown argument: $1"
        ;;
    esac
  done
}

installer_url() {
  if [[ -n "$REQUESTED_VERSION" ]]; then
    [[ "$REQUESTED_VERSION" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]] \
      || fail "release tag must match vMAJOR.MINOR.PATCH"
    printf 'https://github.com/%s/releases/download/%s/install.sh\n' \
      "$REPOSITORY" "$REQUESTED_VERSION"
    return
  fi

  printf 'https://github.com/%s/releases/latest/download/install.sh\n' "$REPOSITORY"
}

main() {
  local installer url

  parse_args "$@"
  require_command curl
  require_command grep
  require_command mktemp

  TEMPORARY="$(mktemp -d "${TMPDIR:-/tmp}/polaris-bootstrap.XXXXXX")"
  trap cleanup EXIT
  installer="$TEMPORARY/install.sh"
  url="$(installer_url)"

  curl --proto '=https' --tlsv1.2 --fail --silent --show-error --location \
    --output "$installer" "$url"

  grep -Fq '# Generated by Incur. Do not edit.' "$installer" \
    || fail "downloaded release installer is not an Incur-generated Polaris installer"

  if [[ -n "$INSTALL_DIR_OVERRIDE" ]]; then
    POLARIS_INSTALL_DIR="$INSTALL_DIR_OVERRIDE" \
      INSTALL_DIR="$INSTALL_DIR_OVERRIDE" \
      sh "$installer"
    return
  fi

  sh "$installer"
}

main "$@"
